version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Choose appropriate Java version
    steps:
      - checkout

      # Setup Maven
      - run: sudo apt-get install -y maven

      # Run Maven build
      - run: mvn -B clean install

workflows:
  version: 2
  build:
    jobs:
      - build
