version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Choose appropriate Java version
    steps:
      - checkout
      
      # Install any dependencies or tools your project needs
      # For example, if your project requires Maven:
      # - run: sudo apt-get install -y maven
      
      # Run your build commands
      - run:
          name: Compile Java source files
          command: javac src/base/*.java  # Compile your Java source file without specifying an output directory
      - run:
          name: Run Java program
          command: java -cp src base.TestCase  # Replace 'base.TestCase' with the fully qualified name of your main class

workflows:
  version: 2
  build:
    jobs:
      - build
